### PR TITLE
Appetizer/fix header links

### LINKED ISSUE #12: Mobile menu github link not working

### PR DESCRIPTION
**Pull request by timmybytes**
Closes #12 #13 #14

### CODE REVIEW

File: src/components/Header/Header.tsx [hunk 1]
```diff
@@ -43,17 +55,29 @@ export const Header = ({ ...rest }): React.ReactElement => {
   const [show, setShow] = useState(false)
   const toggleMenu = () => setShow(!show)
 
+  useEffect(() => {
+    setShow(false)
+  }, [])
+
```
Comment (timmybytes) [inline src/components/Header/Header.tsx:61]: This ends up being redundant, since default state on component mounting is set the same anyway
